# Example: bulk-importing existing clients via the list resource.
#
# 1. Run `terraform query -generate-config-out=generated.tf` with the
#    accompanying bulk-import.tfquery.hcl to discover matching clients.
# 2. Terraform writes a generated.tf similar to the block below.
# 3. Review, adjust, then run `terraform apply` to bring the clients under
#    management.

# --- generated by `terraform query` (example output) ---

resource "unifi_client" "server_0" {
  mac  = "aa:bb:cc:11:22:33"
  name = "web-server-01"

  fixed_ip         = "10.0.10.10"
  local_dns_record = "web-server-01.example.internal"

  network_members_group_ids = ["<group-id-a>", "<group-id-b>"]

  site = "default"

  # Terraform-only lifecycle flags — adjust as needed.
  allow_existing         = true
  skip_forget_on_destroy = false
}

import {
  to       = unifi_client.server_0
  provider = unifi
  identity = {
    mac = "aa:bb:cc:11:22:33"
  }
}

resource "unifi_client" "server_1" {
  mac  = "aa:bb:cc:44:55:66"
  name = "db-server-01"

  fixed_ip         = "10.0.10.20"
  local_dns_record = "db-server-01.example.internal"

  network_members_group_ids = ["<group-id-a>", "<group-id-b>"]

  site = "default"

  allow_existing         = true
  skip_forget_on_destroy = false
}

import {
  to       = unifi_client.server_1
  provider = unifi
  identity = {
    mac = "aa:bb:cc:44:55:66"
  }
}
