name: Acceptance Tests
on:
  release:
    types: [published]
  schedule:
    - cron: "0 13 * * *"

# OIDC token is needed to authenticate uploads to Codecov.
permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Matrix Test
    runs-on: ubuntu-latest
    timeout-minutes: 75
    strategy:
      fail-fast: false
      matrix:
        unifi_version:
          - "latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      # Pre-install Teraform, so that test cases don't try installing their temporary copy
      # See https://github.com/hashicorp/terraform-plugin-testing/issues/429
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_wrapper: false

      # The acceptance tests sometimes timeout for some unknown reason.
      - name: TF acceptance tests
        uses: "nick-fields/retry@v4"
        with:
          timeout_minutes: 20
          max_attempts: 3
          command: make testacc TEST_TIMEOUT=1h UNIFI_STDOUT=true UNIFI_VERSION=${{ matrix.unifi_download_url && 'beta' || matrix.unifi_version }} UNIFI_DOWNLOAD_URL=${{ matrix.unifi_download_url }}
          retry_on: "timeout"

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          use_oidc: true
          flags: acceptance

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          flags: acceptance